task_project/task_app/urls.py
from django.urls import path

from .views import (
    index,
    RecordCreateView,
    delete_object,
)

app_name = 'task_app'
urlpatterns = [
    path('', index, name='index'),
    path('record/', RecordCreateView.as_view(), name='record'),
    path('delete/<int:id_for_del>/', delete_object, name='delete')
]

task_project/task_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task_project/task_app/models.py
from datetime import datetime

from django.db import models

from django.utils.translation import gettext_lazy as _


class BShop(models.Model):
    """Модель барбершопа"""
    name = models.CharField(
        max_length=20,
        verbose_name=_('Название'),
    )
    address = models.CharField(
        max_length=40,
        verbose_name=_('Адрес'),
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Барбершоп')
        verbose_name_plural = _('Барбершопы')
        ordering = ['name']


class Record(models.Model):
    """Модель записи"""
    name = models.CharField(
        max_length=20,
        verbose_name=_('Имя клиента'),
    )

    barber_name = models.CharField(
        max_length=20,
        verbose_name=_('Имя сотрудника'),
    )

    today = int(datetime.now().day)
    month = int(datetime.now().month)

    if month == 2:
        if today == 28:
            month += 1
            today = 0
    if month in (4, 6, 9, 11):
        if today == 30:
            month += 1
            today = 0
    if month in (1, 3, 5, 7, 8, 10, 12):
        if today == 31:
            month += 1
            today = 0
    if month > 12:
        month = 1

    record_date_CHOICES = [
        (None, 'Выберите дату записи'),
        ('tomorrow_12', f'{str(today + 1)}.{str(month)} в 12:00'),
        ('tomorrow_16', f'{str(today + 1)}.{str(month)} в 16:00'),
        ('tomorrow_20', f'{str(today + 1)}.{str(month)} в 20:00'),
        ('d_a_tomorrow_12', f'{str(today + 2)}.{str(month)} в 12:00'),
        ('d_a_tomorrow_16', f'{str(today + 2)}.{str(month)} в 16:00'),
        ('d_a_tomorrow_20', f'{str(today + 2)}.{str(month)} в 20:00'),
    ]

    record_date = models.CharField(
        max_length=40,
        choices=record_date_CHOICES,
        verbose_name='Дата записи',
    )

    bshop = models.ForeignKey(
        BShop,
        on_delete=models.PROTECT,
        verbose_name='Барбершоп',
    )

    class Meta:
        verbose_name = _('Запись')
        verbose_name_plural = _('Записи')
        ordering = ['record_date']

task_project/task_app/forms.py
from django.forms import ModelForm

from .models import Record


class RecordForm(ModelForm):
    class Meta:
        model = Record
        fields = (
            'name',
            'barber_name',
            'record_date',
            'bshop',
        )

task_project/task_app/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView

from task_app.forms import RecordForm
from task_app.models import (
    Record,
    BShop,
)


def index(request):
    bshops = BShop.objects.all()
    records = Record.objects.all()
    context = {
        'bshops': bshops,
        'records': records
    }
    return render(
        request=request,
        template_name='task_app/index.html',
        context=context,
    )


def output_object(request: HttpRequest) -> HttpResponse:
    records = Record.objects.all()
    context = {
        'records': records
    }
    return render(
        request=request,
        template_name='task_app/index.html',
        context=context,
    )


def delete_object(request: HttpRequest, id_for_del: int) -> HttpResponse:
    Record.objects.filter(pk=id_for_del).delete()

    return redirect('task_app:index')


class RecordCreateView(CreateView):
    template_name = 'task_app/create.html'
    form_class = RecordForm
    success_url = reverse_lazy('task_app:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['bshops'] = BShop.objects.all()
        return context

task_project/task_app/templates/layout/basic.html
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
        <title>Главная :: Страница записей</title>
        <link rel="stylesheet" type="text/css" href="{% static 'task_app/style.css' %}">
    </head>
    <body>
        <header>
            <h1> Записи </h1>
        </header>
        <nav>
            <a href="{% url 'task_app:index' %}">Главная</a>
            <a href="{% url 'task_app:record' %}">Записаться</a>
            <hr>
            {% for bshop in bshops %}
                <a>{{ bshop.name }}</a>
            {% endfor %}
        </nav>
        <section>
            {% block content %}
            {% endblock %}
        </section>
    </body>
</html>

task_project/task_app/templates/task_app/create.html
{% extends "layout/basic.html" %}
{% block title %} Добавление Заявки {% endblock %}
{% block content %}
<h2>Добавление заявки</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Добавить">
</form>
{% endblock %}

task_project/task_app/templates/task_app/index.html
{% extends "layout/basic.html" %}
{% block content %}
{% for record in records %}
<div>
    <h2>{{ forloop.counter }}. {{record.name }} </h2>
    <p>{{ record.barber_name }}</p>
    <p><a href="/{{ bshop.pk }}/">{{ record.bshop.name }}</a></p>
    <p>{{ record.get_record_date_display}}</p>
    <a href="{% url 'task_app:delete' record.pk %}">Удалить</a>
</div>
{% endfor %}
{% endblock %}